finish hw2 hw3
lindlind/gallery pull request #1
Opened 2019-03-12 18:13 UTC by lindlind

hw2:
Реализовал бесконечный список картинок, по клику открывается хайрез, есть master-detail

hw3:
сохраняю в памяти уже загруженные картинки в интернал, есть сервисы для непрерывного процесса загрузки

2019-03-13 14:49 UTC, aleksej-lapenok requested changes

2019-03-13 14:49 UTC, aleksej-lapenok commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
файлы идеи не нужны здесь

2019-03-13 14:49 UTC, aleksej-lapenok commented on app/src/main/java/com/lind/vladimir/gallery/DetailFragment.kt
> +        val image = bundle!!.getSerializable("image") as Image
не безопасно

2019-03-13 14:49 UTC, aleksej-lapenok commented on app/src/main/java/com/lind/vladimir/gallery/DetailFragment.kt
> +        Glide.with(context!!)
нельзя использовать Glide в этих домашках

2019-03-13 14:49 UTC, aleksej-lapenok commented on app/src/main/java/com/lind/vladimir/gallery/Utils.kt
> +                e.printStackTrace()
информацию в логах об этом ты не увидишь никогда

2019-03-13 14:49 UTC, aleksej-lapenok commented on app/src/main/java/com/lind/vladimir/gallery/Utils.kt
> +                val ipProcess = runtime.exec("/system/bin/ping -c 1 8.8.8.8")
??? максимально странное решение

2019-03-13 14:49 UTC, aleksej-lapenok commented on app/src/main/java/com/lind/vladimir/gallery/Utils.kt
> +            GlobalScope.launch(Dispatchers.IO) {
корутины тоже нельзя использовать

2019-03-13 14:49 UTC, aleksej-lapenok commented on app/src/main/java/com/lind/vladimir/gallery/env.kt
> +const val INTERNAL_COVER_STORAGE = "/data/user/0/com.lind.vladimir.gallery/app_Covers/"
очень странные пути, которые зависят от устройства
если используешь их, то надо перестать использовать

2019-03-13 14:49 UTC, aleksej-lapenok commented on app/src/main/res/layout/preview_item.xml
> +    <com.lind.vladimir.gallery.SquareImageView
тут должен быть imageView

2019-03-13 19:29 UTC, lindlind commented on app/src/main/java/com/lind/vladimir/gallery/DetailFragment.kt
> +        val image = bundle!!.getSerializable("image") as Image
исправлено

2019-03-13 19:36 UTC, lindlind commented on app/src/main/java/com/lind/vladimir/gallery/DetailFragment.kt
> +        Glide.with(context!!)
На сколько я понимаю, глайд нельзя, потому что в этих домашках мы должны уметь справляться без него. В коде используется класс ImageLoaderService, который реализует то, что могло бы быть реализовано с помощью глайда.

2019-03-13 19:37 UTC, lindlind commented on app/src/main/java/com/lind/vladimir/gallery/Utils.kt
> +                e.printStackTrace()
исправлено (удалено)

2019-03-13 19:37 UTC, lindlind commented on app/src/main/java/com/lind/vladimir/gallery/Utils.kt
> +                val ipProcess = runtime.exec("/system/bin/ping -c 1 8.8.8.8")
исправлено

2019-03-13 19:39 UTC, lindlind commented on app/src/main/java/com/lind/vladimir/gallery/Utils.kt
> +            GlobalScope.launch(Dispatchers.IO) {
Аналогично с ситуацией с глайдом, в коде используются threadPoolExecutor и intentService, которые могли бы быть реализованы с помощью корутин.

2019-03-13 19:39 UTC, lindlind commented on app/src/main/java/com/lind/vladimir/gallery/env.kt
> +const val INTERNAL_COVER_STORAGE = "/data/user/0/com.lind.vladimir.gallery/app_Covers/"
исправлено

2019-03-13 19:41 UTC, lindlind commented on app/src/main/res/layout/preview_item.xml
> +    <com.lind.vladimir.gallery.SquareImageView
Это свой класс, наследующийся от ImageView, в котором переопределены ширина  и высота. В остальном он прямой наследник ImageView.

2019-03-13 19:45 UTC, lindlind commented on .idea/misc.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Понял ошибку. Я могу добавить файлы идеи в .gitignore, но от этого уже не исправит наличие этих файлов в гите. :(

2019-03-14 11:02 UTC, lindlind commented
Все замечания учтены в следующем пулл реквесте

2019-03-14 11:02 UTC, closed without merging